export type SchemeCategory = "Start" | "Fund" | "Innovate" | "Market" | "Build skills" | "Register";

export interface OfficialScheme {
  readonly id: string;
  readonly title: string;
  readonly shortTitle: string;
  readonly category: SchemeCategory;
  readonly authority: string;
  readonly summary: string;
  readonly support: string;
  readonly audience: string;
  readonly sourceUrl: string;
  readonly verifiedOn: string;
  readonly statusNote?: string;
  readonly featured?: boolean;
}

/**
 * Curated discovery records, not eligibility rules. Claims are intentionally
 * conservative and link directly to the responsible government authority.
 */
export const officialSchemes: readonly OfficialScheme[] = [
  {
    id: "pmegp",
    title: "Prime Minister’s Employment Generation Programme",
    shortTitle: "PMEGP",
    category: "Start",
    authority: "Ministry of MSME · KVIC",
    summary: "Credit-linked support for establishing new micro-enterprises in the non-farm sector.",
    support: "Project support for new manufacturing and service enterprises",
    audience: "Aspiring and first-generation entrepreneurs",
    sourceUrl:
      "https://www.msme.gov.in/offerings/schemes-and-services/details/prime-minister-employment-generation-programme-and-other-credit-support-schemes-1-MDMzETMtQWa",
    verifiedOn: "13 Jul 2026",
    featured: true,
  },
  {
    id: "cgtmse",
    title: "Credit Guarantee Scheme for Micro and Small Enterprises",
    shortTitle: "CGTMSE",
    category: "Fund",
    authority: "Ministry of MSME · CGTMSE",
    summary: "Guarantee support that enables eligible lenders to extend collateral-free credit to MSEs.",
    support: "Credit guarantee through registered member lending institutions",
    audience: "Eligible micro and small enterprises seeking institutional credit",
    sourceUrl: "https://www.cgtmse.in/",
    verifiedOn: "13 Jul 2026",
    featured: true,
  },
  {
    id: "pms",
    title: "Procurement and Marketing Support Scheme",
    shortTitle: "PMS",
    category: "Market",
    authority: "Office of DC (MSME)",
    summary: "Market-access support covering approved fairs, packaging, barcodes and digital commerce activities.",
    support: "Reimbursement or assistance varies by approved component",
    audience: "Micro and small enterprises with a valid Udyam registration",
    sourceUrl:
      "https://www.msme.gov.in/offerings/schemes-and-services/details/marketing-promotion-schemes-1-QzMzETMtQWa",
    verifiedOn: "13 Jul 2026",
  },
  {
    id: "esdp",
    title: "Entrepreneurship and Skill Development Programme",
    shortTitle: "ESDP",
    category: "Build skills",
    authority: "Office of DC (MSME)",
    summary: "Entrepreneurship and skill programmes intended to promote new enterprises and strengthen existing MSMEs.",
    support: "Awareness, entrepreneurship and skill-development programmes",
    audience: "Aspiring entrepreneurs and existing MSMEs",
    sourceUrl:
      "https://www.msme.gov.in/offerings/schemes-and-services/details/entrepreneurship-and-skill-development-programs-gzMxMTMtQWa",
    verifiedOn: "13 Jul 2026",
  },
  {
    id: "udyam",
    title: "Udyam Registration",
    shortTitle: "Udyam",
    category: "Register",
    authority: "Ministry of MSME",
    summary: "The official, free and paperless government registration route for micro, small and medium enterprises.",
    support: "Permanent registration number and online certificate",
    audience: "People intending to establish or register an MSME",
    sourceUrl: "https://www.udyamregistration.gov.in/default.aspx",
    verifiedOn: "13 Jul 2026",
    featured: true,
  },
  {
    id: "mudra",
    title: "Pradhan Mantri MUDRA Yojana",
    shortTitle: "PMMY",
    category: "Fund",
    authority: "Department of Financial Services",
    summary: "An official institutional-credit pathway for income-generating micro enterprises in manufacturing, trading and services.",
    support: "Loans are delivered through participating lending institutions",
    audience: "Non-corporate, non-farm micro enterprises exploring formal credit",
    sourceUrl: "https://financialservices.gov.in/pradhan-mantri-mudra-yojana-pmmy",
    verifiedOn: "15 Jul 2026",
    statusNote: "Lender assessment applies",
  },
  {
    id: "sisfs",
    title: "Startup India Seed Fund Scheme",
    shortTitle: "SISFS",
    category: "Innovate",
    authority: "DPIIT · Startup India",
    summary: "Seed-support pathway for proof of concept, prototype development, product trials, market entry and commercialisation.",
    support: "Support is routed through approved incubators",
    audience: "DPIIT-recognised early-stage startups reviewing current programme terms",
    sourceUrl: "https://seedfund.startupindia.gov.in/",
    verifiedOn: "15 Jul 2026",
    statusNote: "Verify the current application window",
    featured: true,
  },
  {
    id: "cgss",
    title: "Credit Guarantee Scheme for Startups",
    shortTitle: "CGSS",
    category: "Fund",
    authority: "DPIIT · Startup India",
    summary: "A credit-guarantee framework supporting eligible lending to recognised startups through approved institutions.",
    support: "Guarantee framework; not a direct loan or approval",
    audience: "DPIIT-recognised startups and participating financial institutions",
    sourceUrl: "https://www.startupindia.gov.in/content/dam/invest-india/cgss/cgss-guidelines.pdf",
    verifiedOn: "15 Jul 2026",
    statusNote: "May 2025 guidelines",
  },
  {
    id: "nidhi-prayas",
    title: "NIDHI–PRAYAS",
    shortTitle: "PRAYAS",
    category: "Innovate",
    authority: "Department of Science and Technology",
    summary: "A proof-of-concept support component within the NIDHI entrepreneurship and innovation programme.",
    support: "Delivered through participating PRAYAS centres and incubators",
    audience: "Innovators developing technology-oriented prototypes",
    sourceUrl: "https://nidhi.dst.gov.in/schemes-programmes/",
    verifiedOn: "15 Jul 2026",
    statusNote: "Centre-specific calls apply",
  },
  {
    id: "birac-big",
    title: "Biotechnology Ignition Grant",
    shortTitle: "BIG",
    category: "Innovate",
    authority: "BIRAC · Department of Biotechnology",
    summary: "A call-based programme supporting early biotechnology ideas as they move toward proof of concept.",
    support: "Programme support is governed by the current published call",
    audience: "Biotechnology innovators and eligible early-stage ventures",
    sourceUrl: "https://www.birac.nic.in/big.php",
    verifiedOn: "15 Jul 2026",
    statusNote: "Call based",
  },
  {
    id: "tide-2",
    title: "Technology Incubation and Development of Entrepreneurs",
    shortTitle: "TIDE 2.0",
    category: "Innovate",
    authority: "Ministry of Electronics and IT",
    summary: "Incubation support for entrepreneurship using ICT and emerging technologies through selected centres.",
    support: "Access is routed through participating incubation centres",
    audience: "Technology innovators and startups reviewing centre-specific opportunities",
    sourceUrl: "https://www.meity.gov.in/offerings/schemes-and-services/details/technology-incubation-and-development-of-entrepreneurs-QMwEjNtQWa",
    verifiedOn: "15 Jul 2026",
    statusNote: "Incubator availability varies",
  },
  {
    id: "samridh",
    title: "SAMRIDH Accelerator Programme",
    shortTitle: "SAMRIDH",
    category: "Innovate",
    authority: "MeitY Startup Hub",
    summary: "An accelerator-led pathway intended to help qualifying technology startups improve product and market readiness.",
    support: "Cohort and accelerator-based support",
    audience: "Technology startups seeking structured acceleration",
    sourceUrl: "https://msh.meity.gov.in/schemes/samridh",
    verifiedOn: "15 Jul 2026",
    statusNote: "Verify active cohorts",
  },
  {
    id: "aspire",
    title: "A Scheme for Promotion of Innovation, Rural Industries and Entrepreneurship",
    shortTitle: "ASPIRE",
    category: "Start",
    authority: "Ministry of MSME",
    summary: "An entrepreneurship and incubation pathway focused on rural and agro-based enterprise development.",
    support: "Implemented substantially through Livelihood Business Incubators",
    audience: "Rural and agro-industry entrepreneurs and participating institutions",
    sourceUrl: "https://www.aspire.msme.gov.in/ASPIRE/AFHome.aspx",
    verifiedOn: "15 Jul 2026",
  },
  {
    id: "msme-zed",
    title: "MSME Sustainable Certification",
    shortTitle: "ZED",
    category: "Build skills",
    authority: "Ministry of MSME",
    summary: "A quality and sustainability improvement pathway for MSMEs pursuing Zero Defect Zero Effect practices.",
    support: "Certification and approved quality-improvement components",
    audience: "Registered MSMEs working on quality, productivity and sustainability",
    sourceUrl: "https://www.msme.gov.in/offerings/schemes-and-services/details/technology-upgradation-and-quality-certification-kjNzETMtQWa",
    verifiedOn: "15 Jul 2026",
  },
  {
    id: "pmfme",
    title: "PM Formalisation of Micro Food Processing Enterprises",
    shortTitle: "PMFME",
    category: "Start",
    authority: "Ministry of Food Processing Industries",
    summary: "A formalisation and capacity-building programme for eligible micro food-processing enterprises and groups.",
    support: "Multiple components governed by current scheme guidelines",
    audience: "Micro food-processing enterprises and eligible groups",
    sourceUrl: "https://pmfme.mofpi.gov.in/",
    verifiedOn: "15 Jul 2026",
    statusNote: "Check state and component availability",
  },
  {
    id: "pm-vishwakarma",
    title: "PM Vishwakarma",
    shortTitle: "Vishwakarma",
    category: "Build skills",
    authority: "Ministry of MSME",
    summary: "A programme covering specified traditional trades through skill, toolkit, credit and market-support components.",
    support: "Trade-specific components and verification apply",
    audience: "Artisans and craftspeople in the programme’s notified trades",
    sourceUrl: "https://pmvishwakarma.gov.in/",
    verifiedOn: "15 Jul 2026",
  },
  {
    id: "startup-recognition",
    title: "DPIIT Startup Recognition",
    shortTitle: "Recognition",
    category: "Register",
    authority: "DPIIT · Startup India",
    summary: "The official recognition route used to access applicable Startup India services and regulatory support.",
    support: "Recognition certificate subject to current published criteria",
    audience: "Eligible companies, partnerships and LLPs building innovative or scalable ventures",
    sourceUrl: "https://www.startupindia.gov.in/content/sih/en/startup-scheme.html",
    verifiedOn: "15 Jul 2026",
  },
] as const;

export const schemeCategories: readonly ("All" | SchemeCategory)[] = [
  "All",
  "Start",
  "Fund",
  "Innovate",
  "Market",
  "Build skills",
  "Register",
];
